//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RegisteredParents
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NIC { get; set; }
        public string Email { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
